name: Docker Image CI

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Azure Container Registry Login
        uses: Azure/docker-login@v1
        with:
          # Container registry username
          username: ${{ secrets.USERNAME }}
          # Container registry password
          password: ${{ secrets.PASSWORD }}
          # Container registry server url
          login-server: ${{ secrets.SERVER }}

      - uses: actions/checkout@v3
      - name: Build the Docker image
        run:
          docker build . --file Dockerfile --tag regmaterialflow.azurecr.io/materialflowfuncs:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
          docker push regmaterialflow.azurecr.io/materialflowfuncs:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
